name: bpf-ci

on:
  pull_request:

concurrency: 
  group: ci-test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  llvm-toolchain:
    runs-on: ubuntu-latest
    outputs:
      llvm: ${{ steps.llvm-toolchain-impl.outputs.version }}
    steps:
      - id: llvm-version
        uses: chantra/ci/get-llvm-version@aarch64_img
      - id: llvm-toolchain-impl
        shell: bash
        run: echo "::set-output name=version::llvm-${{ steps.llvm-version.outputs.version }}"
  set-matrix:
    needs: llvm-toolchain
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.set-matrix-impl.outputs.build_matrix }}
      test-matrix: ${{ steps.set-matrix-impl.outputs.test_matrix }}
    steps:
      - id: set-matrix-impl
        shell: python3 -I {0}
        run: |
          from json import dumps

          matrix = [
            {"kernel": "LATEST", "runs_on": ["ARM64", "self-hosted"], "arch": "aarch64", "toolchain": "gcc"},
          ]


          build_matrix = {"include": matrix}
          print(f"::set-output name=build_matrix::{dumps(build_matrix)}")

          tests = ["test_progs", "test_progs_no_alu32", "test_maps", "test_verifier"]
          test_matrix = {"include": [{**config, **{"test": test}}
                                      for config in matrix
                                        for test in tests]}
          print(f"::set-output name=test_matrix::{dumps(test_matrix)}")
  build:
    name: build for ${{ matrix.arch }} with ${{ matrix.toolchain }}
    needs: set-matrix
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.set-matrix.outputs.build-matrix) }}
    env:
      KERNEL: ${{ matrix.kernel }}
      REPO_ROOT: ${{ github.workspace }}
      REPO_PATH: ""
    steps:
      - uses: actions/checkout@v2
      - if: ${{ github.repository == 'kernel-patches/vmtest' }}
        name: Download bpf-next tree
        uses: chantra/ci/get-linux-source@aarch64_img
        with:
          dest: '.kernel'
      - if: ${{ github.repository == 'kernel-patches/vmtest' }}
        name: Move linux source in place
        shell: bash
        run: |
          rm -rf .kernel/.git
          cp -rf .kernel/. .
          rm -rf .kernel
      - uses: chantra/ci/patch-kernel@aarch64_img
        with:
          patches-root: '${{ github.workspace }}/ci/diffs'
          repo-root: '${{ github.workspace }}'
      - name: Setup build environment
        uses: chantra/ci/setup-build-env@aarch64_img
      - name: Build kernel image
        uses: chantra/ci/build-linux@aarch64_img
        with:
          arch: ${{ matrix.arch }}
          toolchain: ${{ matrix.toolchain }}
      - name: Build selftests
        uses: chantra/ci/build-selftests@aarch64_img
        with:
          vmlinux_btf: ${{ github.workspace }}/vmlinux
          toolchain: ${{ matrix.toolchain }}
      - name: Build samples
        uses: chantra/ci/build-samples@aarch64_img
        with:
          vmlinux_btf: ${{ github.workspace }}/vmlinux
          toolchain: ${{ matrix.toolchain }}
      - name: Tar artifacts
        run: |
          file_list=""
          if [ "${{ github.repository }}" == "kernel-patches/vmtest" ]; then
            # Package up a bunch of additional infrastructure to support running
            # 'make kernelrelease' and bpf tool checks later on.
            file_list="$(find . -iname Makefile | xargs) \
              scripts/ \
              tools/testing/selftests/bpf/ \
              tools/include/ \
              tools/bpf/bpftool/";
          fi

          tar -czf vmlinux-${{ matrix.arch }}-${{ matrix.toolchain }}.tar.gz \
            .config \
            arch/*/boot/*Image* \
            include/config/auto.conf \
            include/generated/autoconf.h \
            ${file_list} \
            --exclude '*.h' \
            selftests/bpf/ \
            vmlinux
      - uses: actions/upload-artifact@v3
        with:
          name: vmlinux-${{ matrix.arch }}-${{ matrix.toolchain }}
          if-no-files-found: error
          path: vmlinux-${{ matrix.arch }}-${{ matrix.toolchain }}.tar.gz
  test:
    name: ${{ matrix.test }} on ${{ matrix.arch }} with ${{ matrix.toolchain }}
    needs: [set-matrix, build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.set-matrix.outputs.test-matrix) }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 100
    env:
      KERNEL: ${{ matrix.kernel }}
      REPO_ROOT: ${{ github.workspace }}
      REPO_PATH: ""
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v3
        with:
          name: vmlinux-${{ matrix.arch }}-${{ matrix.toolchain }}
          path: .
      - name: Untar artifacts
        run: tar -xzf vmlinux-${{ matrix.arch }}-${{ matrix.toolchain }}.tar.gz
      - name: Prepare rootfs
        uses: chantra/ci/prepare-rootfs@aarch64_img
        with:
          project-name: 'libbpf'
          arch: ${{ matrix.arch }}
          kernel: ${{ matrix.kernel }}
          kernel-root: '.'
          image-output: '/tmp/root.img'
          test: ${{ matrix.test }}
      - name: Run selftests
        uses: chantra/ci/run-qemu@aarch64_img
        with:
          arch: ${{ matrix.arch}}
          img: '/tmp/root.img'
          vmlinuz: '${{ github.workspace }}/vmlinuz'
          kernel-root: '.'
